#! perl

=pod

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.

L<https://projecteuler.net/problem=2>

=cut

$n = 4_000_000;
$f1 = 1; $f2 = 2;
$sum = 2;
while ($_ < $n) {
  $_ = $f1 + $f2;
  $sum += $_ if ($_ % 2 == 0);
  $f1 = $f2;
  $f2 = $_;
}
print $sum;
