#! perl

=pod

Highly divisible triangular number
Published on 08 March 2002 at 06:00 pm [Server Time]

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 
1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five
hundred divisors?

L<https://projecteuler.net/problem=12>

=cut

use integer;
$int::x = 0; # only for perlcc -O -O1 types
my $max = shift || 500;

sub num_divisors {
  my int $n = shift;
  my @div;
  for my int $i (2 .. int(sqrt($n))) { # first the prime factors
    push @div, $i if $n % $i == 0;
  }
  my int $numdivs = 2 + scalar @div; # always 1 and $n
  for my int $i (@div) { # now only the prime factors
    $numdivs++ if $n / $i != $i;
  }
  $numdivs;
}

my int $i = 1;
my int $n = 1;
while ($i++) {
  $n += $i;
  # hard-coded precomputed results to speed up higher numbers
  next if $max >= 100 and $n < 73920;
  next if $max >= 200 and $n < 2031120;
  next if $max >= 300 and $n < 2162160;
  next if $max >= 400 and $n < 17907120;
  next if $max >= 500 and $n < 76576500;
  if (num_divisors($n) >= $max) {
    print $n;
    exit;
  }
}
